name: wxprofilers-docs
channels:
  - conda-forge
  - mutirri
dependencies:
  - gfortran_linux-64 
  - cython
  - matplotlib
  - numpy
  - pandas
  - scipy
  - sphinxcontrib-apidoc
  - sphinxcontrib-bibtex
  - sphinxcontrib-napoleon
  - statsmodels
  - xarray