name: wxprofilers-docs
channels:
  - conda-forge
dependencies:
  - gfortran_linux-64
  - cython
  - matplotlib
  - numpy
  - pandas
  - scipy
  - sphinxcontrib-apidoc
  - sphinxcontrib-bibtex
  - statsmodels
  - xarray